version: "3"
services:
  db:
    # container_name: pg_container
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      # POSTGRES_USER: root
      POSTGRES_PASSWORD: pass123
      # POSTGRES_DB: test_db
