# version: "3"
# services:
#   db:
#     # container_name: pg_container
#     image: postgres
#     restart: always
#     ports:
#       - "5432:5432"
#     environment:
#       # POSTGRES_USER: root
#       POSTGRES_PASSWORD: pass123
#       # POSTGRES_DB: test_db

version: '3.9'

services:
  app_dev:
    container_name: nestjs_course_dev
    build:
      context: .
      target: development
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
      - 9229:9229
    command: npm run start:debug
    env_file:
      - .env
    networks:
      - webnet
    depends_on:
      - postgres
  postgres:
    container_name: postgres_container
    image: postgres:13.3
    restart: always
    networks:
      - webnet
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
      PG_DATA: /var/lib/postgresql/data
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - pgdata:/var/lib/postgresql/data
networks:
  webnet:
volumes:
  pgdata: